### ISSUE TITLE
謝謝你完成作業

### ISSUE THREAD

**Issue by azole** [ouyangyuro/git-workshop#1]
在 readme 整理的 git 筆記很棒，影片心得也寫得很好，我特別喜歡你分享的這個總結

> 會時也可以去教導別人，因為在教導別人時自己其實也在同時進步。

超級同意，我自己的經驗是，很多時候覺得自己懂了，到了要教別人的時候才發現自己吱吱嗚嗚的，解釋的不是很好，那時候就會知道其實自己並不是真的完全懂了，到了多分享幾次後，不但協助自己釐清了整個思緒，也加深了自己的印象，一舉數得。之後在課堂上或工作上，如果有機會，都要保持這樣的習慣，分享與協助別人，共勉之。

**Comment by ouyangyuro** [comment]
謝謝!老師的feedback!

**Comment by huangyutong** [comment]
謝謝老師～～
